### Welcome message
GET https://localhost:8080

### Wrong url
GET http://localhost:8080/wrong-url

### Wrong body
POST http://localhost:8080/login

### User not found
POST http://localhost:8080/login
content-type: application/json

{
    "email": "ciccio@email.it",
    "password": "sssssss!"
}


### Wrong password
POST http://localhost:8080/login
content-type: application/json

{
    "email": "pippo.baudo@rai.it",
    "password": "wrongwrongwrong!"
}


### User OK
POST http://localhost:8080/login
content-type: application/json

{
    "email": "pippo.baudo@rai.it",
    "password": "123secretPWD"
}


### test
POST http://localhost:8080/login
content-type: application/x-www-form-urlencoded

email=pippobaudo&password=123secretPWD
